FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

ADD ./requirements.txt /app
ADD ./requirements-dev.txt /app
ADD ./alembic /app/alembic
ADD ./main.py /app
ADD ./alembic.ini /app
ADD ./tests /app/tests
ADD ./pyproject.toml /app

RUN pip install --upgrade pip  \
    && pip install --no-cache-dir -r /app/requirements.txt  \
    && pip install --no-cache-dir -r /app/requirements-dev.txt

ADD ./docker /app/docker
ADD ./app/ /app/app
