version: '3.7'

services:
  db:
    container_name: itfits_db_local
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql@16/data/
    networks:
      - dockernet
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    container_name: ${COMPOSE_PROJECT_NAME}.itfits-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/docker/backend/asgi-entrypoint.sh
    ports:
      - 8000:8000
    networks:
      - dockernet
    volumes:
      - type: bind
        source: ./logs/
        target: /app/logs/
      - storage:/app/storage
    env_file:
      - .env
    depends_on:
      - db

networks:
  dockernet:
    external:
      name: dockernet

volumes:
  storage:
    external: true
  postgres_data:
