"""add_title_in_calendar

Revision ID: e50be67ead00
Revises: e9e87652f077
Create Date: 2024-06-12 21:42:54.959684

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e50be67ead00"
down_revision = "e9e87652f077"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_params",
        sa.Column("id", sa.Uuid(), server_default=sa.FetchedValue(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.FetchedValue(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("calendars", sa.Column("title", sa.String(), nullable=True))
    op.drop_constraint("calendars_assigner_id_fkey", "calendars", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "calendars_assigner_id_fkey",
        "calendars",
        "users",
        ["assigner_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("calendars", "title")
    op.drop_table("user_params")
    # ### end Alembic commands ###
