"""edit_phone_to_tegeram_url

Revision ID: b57374c32b69
Revises: e50be67ead00
Create Date: 2024-06-18 01:16:50.811344

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b57374c32b69"
down_revision = "e50be67ead00"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_url", sa.String(), nullable=True))
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "telegram_url")
    # ### end Alembic commands ###
